# Generated by Django 4.0.5 on 2022-06-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='firstname',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='lastname',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
