# Generated by Django 4.0.5 on 2022-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usermaster_email_alter_usermaster_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('name', models.TextField(max_length=50)),
                ('auther', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=50)),
            ],
        ),
    ]
